#                                                  NUMPY ESSENTIALS 

### PART 1

As a fundamental package for scientific computing, Numpy provides the foundation of mathematical , scientific, engineering, 
and data science  programming  within the Python Echo-system. Numpy's main object is the homogeneous multidimentional array.

### Here are some key features of NumPy:

##### Arrays:
NumPy introduces a powerful N-dimensional array object, ndarray, which is more efficient than Python's built-in lists for numerical computations.

##### Mathematical Functions:
NumPy offers a wide range of mathematical operations like trigonometric, statistical, and algebraic functions that can be applied to arrays.

##### Linear Algebra:
It provides functions for linear algebra operations, including matrix multiplication, eigenvalues, and more.

##### Random Number Generation: 
NumPy has a module for generating random numbers, which is useful in simulations and statistical sampling.

##### Interoperability:
NumPy arrays can be easily integrated with other libraries like Pandas, Matplotlib, and SciPy, making it a central tool in the Python scientific computing ecosystem.

##### Performance:
NumPy operations are implemented in C, making them much faster than similar operations in pure Python.

In summary, NumPy is essential for anyone working with numerical data in Python, especially in fields like data science, machine learning, and scientific computing.

In [2]:
import numpy as np

Lets start with numpy arrays : Vectors (One-D array) & Matrices (Two-D arrays, can still have one row or one column)
    We can create numpy array with python datatypes Tuples and lists 

In [3]:
my_list = [-1,0,1] #creating a list here

In [4]:
my_list #checking values inside list

[-1, 0, 1]

In [5]:
type(my_list) # checking type of list

list

or

In [7]:
my_list, type(my_list) # here we are performing both steps together

([-1, 0, 1], list)

In [8]:
my_array = np.array(my_list) #we have created numpy array using python list

In [10]:
my_array, type(my_array) #checking array and its type

(array([-1,  0,  1]), numpy.ndarray)

In [11]:
my_matrix = [[1,2,3],[4,5,6],[7,8,9]] # created two D array using lists of list 

In [12]:
my_matrix, type(my_matrix)

([[1, 2, 3], [4, 5, 6], [7, 8, 9]], list)

In [13]:
matrix_one = np.array(my_matrix)

In [15]:
matrix_one, type(matrix_one)

(array([[1, 2, 3],
        [4, 5, 6],
        [7, 8, 9]]),
 numpy.ndarray)

### NOW WE ARE USING THE TUPLE

In [16]:
my_tuple = (-1,0,1)

In [17]:
my_tuple, type(my_tuple)

((-1, 0, 1), tuple)

In [18]:
my_array_t = np.array(my_tuple)

In [19]:
my_array_t, type(my_array_t)

(array([-1,  0,  1]), numpy.ndarray)

### NOW WE ARE USING SOME BUILT IN FUNCTIONS OF NUMPY 

#### 1. arange() 
The arange() function in NumPy is used to create arrays with evenly spaced values within a given interval. 
It’s similar to Python's built-in range() function 
but returns a NumPy array rather than a list, and it offers more flexibility in specifying the spacing between values.

SYNTAX: numpy.arange([start,] stop[, step,], dtype=None)

In [22]:
np.arange(0,11,2) #we can check the documentation with shift tab 

array([ 0,  2,  4,  6,  8, 10])

In [27]:
np.arange(0,11,2, dtype = float) #we can pass the datatype as well

array([ 0.,  2.,  4.,  6.,  8., 10.])

#### 2. Linspace()

The linspace() function in NumPy is used to create an array of evenly spaced numbers over a specified range. 
Unlike arange(),which uses a step size, linspace() is defined by the number of elements you want between a start
and stop value.

SYNTAX : numpy.linspace(start, stop, num=50, endpoint=True, retstep=False, dtype=None, axis=0)

    Parameters:
start (required): The starting value of the sequence.

stop (required): The end value of the sequence.

num (optional): The number of equally spaced samples to generate. The default is 50.

endpoint (optional): If True (default), stop is the last sample. If False, stop is excluded, and the spacing is adjusted.

retstep (optional): If True, the function returns the step size between values in the array along with the array itself.

dtype (optional): The data type of the output array. If not specified, it is inferred.

axis (optional): The axis in the result array along which the values are spaced. Default is 0.

In [31]:
np.linspace(1,15,15) #3rd parameter will give 15 samples from this start and end point

array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
       14., 15.])

In [33]:
np.linspace(1,15,15, retstep = True ) # its telling that step size is 1 by giving 1. value at the end 

(array([ 1.,  2.,  3.,  4.,  5.,  6.,  7.,  8.,  9., 10., 11., 12., 13.,
        14., 15.]),
 1.0)

In [35]:
np.linspace(1,15,30, retstep = True ) # Another example with samples 30 and step size is .48 

(array([ 1.        ,  1.48275862,  1.96551724,  2.44827586,  2.93103448,
         3.4137931 ,  3.89655172,  4.37931034,  4.86206897,  5.34482759,
         5.82758621,  6.31034483,  6.79310345,  7.27586207,  7.75862069,
         8.24137931,  8.72413793,  9.20689655,  9.68965517, 10.17241379,
        10.65517241, 11.13793103, 11.62068966, 12.10344828, 12.5862069 ,
        13.06896552, 13.55172414, 14.03448276, 14.51724138, 15.        ]),
 0.4827586206896552)

In [39]:
# Create an array with 5 numbers between 1 and 10
arr = np.linspace (1,10, num = 5)

In [40]:
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [41]:
# Create an array with 5 numbers between 1 and 10, excluding 10
arr = np.linspace(1, 10, num=5, endpoint=False)
print(arr)

[1.  2.8 4.6 6.4 8.2]


In [43]:
#Create an array and also return the step size
arr, step = np.linspace(1,10,num= 5, retstep = True)
arr

array([ 1.  ,  3.25,  5.5 ,  7.75, 10.  ])

In [44]:
step

2.25

#### 3. zeros()
The zeros() function in NumPy is used to create a new array filled entirely with zeros. 
It’s often used to initialize arrays or matrices in various numerical and data processing tasks.

SYNTAX : numpy.zeros(shape, dtype=float, order='C')

    Parameters:
##### shape (required): 
Specifies the shape of the array. This can be an integer for a 1D array or a tuple of integers for multi-dimensional arrays
(e.g., (rows, columns) for a 2D array).
##### dtype (optional): 
The desired data type for the array. The default is float.
##### order (optional): 
Whether to store multi-dimensional data in row-major (C-style) or 
    column-major (Fortran-style) order. The default is 'C'.

In [45]:
# Create a 1D array of 5 zeros
arr = np.zeros(5)
arr

array([0., 0., 0., 0., 0.])

In [46]:
# Create a 2x3 array of zeros
arr = np.zeros((2, 3))
print(arr)

[[0. 0. 0.]
 [0. 0. 0.]]


In [47]:
arr = np.zeros((2,3), dtype = int)
arr

array([[0, 0, 0],
       [0, 0, 0]])

### 4. ones()

The ones() function in NumPy is used to create a new array filled entirely with ones. 
Like zeros(), it's often used to initialize arrays or matrices, but in this case, with all elements set to one.

SYNTAX = numpy.ones(shape, dtype=None, order='C')

Parameters:
#### shape (required):
Specifies the shape of the array. This can be an integer for a 1D array or a tuple of integers for multi-dimensional arrays (e.g., (rows, columns) for a 2D array).
#### dtype (optional): 
The desired data type for the array. If not specified, it defaults to float.
#### order (optional): 
Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order. The default is 'C'.

In [48]:
# Create a 1D array of 5 ones
arr = np.ones(5)
print(arr)

[1. 1. 1. 1. 1.]


In [50]:
# Create a 2x3 array of ones
arr = np.ones((2,3))
arr

array([[1., 1., 1.],
       [1., 1., 1.]])

In [51]:
# Create a 3x3 array of integer ones
arr = np.ones((3,3), dtype = int)
arr

array([[1, 1, 1],
       [1, 1, 1],
       [1, 1, 1]])

### 5. eye()

The eye() function in NumPy is used to create a 2D array (or matrix) with ones on the diagonal and zeros elsewhere. 
This type of matrix is known as an identity matrix when it is square (i.e., the number of rows equals the number of columns)

SYNTAX = numpy.eye(N, M=None, k=0, dtype=float, order='C')

Parameters:
#### N (required): 
The number of rows in the output array.
#### M (optional): 
The number of columns in the output array. If not provided, M is set to N, resulting in a square matrix.
#### k (optional): 
The index of the diagonal. The default is 0, which refers to the main diagonal. A positive value refers to an upper diagonal, while a negative value refers to a lower diagonal.
#### dtype (optional):
The data type of the output array. The default is float.
#### order (optional): 
Whether to store multi-dimensional data in row-major (C-style) or column-major (Fortran-style) order. The default is 'C'.

In [53]:
# Create a 3x3 identity matrix
arr = np.eye(3)
arr

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [54]:
# Create a 3x4 matrix with ones on the main diagonal
arr = np.eye(3,4)
arr

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.]])

In [55]:
# Create a 3x3 matrix with ones on the first upper diagonal
arr = np.eye(3, k =1)
arr

array([[0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 0.]])

In [56]:
# Create a 3x3 matrix with ones on the first down diagonal
arr = np.eye(3, k = -1)
arr

array([[0., 0., 0.],
       [1., 0., 0.],
       [0., 1., 0.]])

In [57]:
# Create a 3x3 identity matrix with integer type
arr = np.eye(3, dtype = int)
arr

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

### 6.random()

The random() function in NumPy is used to generate random numbers or random arrays. It is part of the numpy.random module, 
which provides a suite of functions for generating random data in various distributions.



#### Basic Usage

In [63]:
# Generate a single random float between 0 and 1
# evertime you run this cell, will give you different random number
random_number = np.random.random()
random_number

0.766640306236073

#### Generating Random Arrays

In [64]:
# Generate a 1D array of 5 random floats between 0 and 1
arr = np.random.random(5)
arr


array([0.53962077, 0.47009255, 0.1328445 , 0.57020542, 0.35523955])

In [65]:
# Generate a 2x3 array of random floats between 0 and 1
arr = np.random.random((2,3))
arr

array([[0.44517224, 0.72895218, 0.54370881],
       [0.51634284, 0.3236563 , 0.27343648]])

#### Some functions used under random

######  (i) The rand() function 
in NumPyis used to generate an array of random numbers that are uniformly distributed between 0 and 1. Unlike random(),
which requires specifying the shape as a tuple, rand() allows you to directly specify the dimensions as separate arguments

##### Generate a single random float between 0 and 1
random_number = np.random.rand()

print(random_number)

##### Generate a 1D array of 5 random floats between 0 and 1
arr = np.random.rand(5)

print(arr)

##### Generate a 2x3 array of random floats between 0 and 1
arr = np.random.rand(2, 3)

print(arr)

##### Generate a 3x3x3 array of random floats between 0 and 1
arr = np.random.rand(3, 3, 3)

print(arr)

The numbers generated by rand() are uniformly distributed in the interval [0.0, 1.0), meaning every number in this range has an equal probability of being selected.

##### (ii) The randn() function 
in NumPy is used to generate an array of random numbers drawn from a standard normal distribution (Gaussian distribution) with a mean of 0 and a standard deviation of 1. 
This function is useful for simulations and data analysis where normally distributed random data is required.

###### Key Points:
    
Normal Distribution: randn() generates values from a standard normal distribution,
    where the mean is 0 and the standard deviation is 1. This is useful in scenarios where data follows a normal distribution.

#### (iii) The randint() function
in NumPy is used to generate random integers within a specified range. 
It is useful for tasks where you need random integer values, such as in simulations, random sampling, and data generation

SYNTAX = numpy.random.randint(low, high=None, size=None, dtype=int)

Parameters:
##### low (required): 
The lower bound (inclusive) of the range of random integers to be generated.
##### high (optional): 
The upper bound (exclusive) of the range. If not specified, low is treated as the upper bound, and the range is [0, low).
##### size (optional):
The shape of the output array. If not specified, a single integer is returned.
##### dtype (optional): 
The data type of the output array. The default is int.

In [66]:
# Generate a single random integer between 0 (inclusive) and 10 (exclusive)
random_integer = np.random.randint(10)
print(random_integer)

8


In [67]:
# Generate a single random integer between 5 (inclusive) and 15 (exclusive)
random_integer = np.random.randint(5, 15)
print(random_integer)

5


In [68]:
# Generate a 1D array of 5 random integers between 0 (inclusive) and 10 (exclusive)
arr = np.random.randint(10, size=5)
print(arr)

[9 0 5 0 3]


In [69]:
# Generate a 2x3 array of random integers between 1 (inclusive) and 20 (exclusive)
arr = np.random.randint(1, 20, size=(2, 3))
print(arr)

[[ 6  8  9]
 [ 7 11  4]]


In [70]:
# Generate a 3x3 array of random integers between 10 (inclusive) and 50 (exclusive) with dtype as int32
arr = np.random.randint(10, 50, size=(3, 3), dtype=np.int32)
print(arr)

[[41 25 48]
 [26 32 44]
 [39 22 20]]


In [72]:
arr = np.random.randint(10, 50,5) #this will give you 5 numbers including 10 and excluding 50
arr

array([48, 11, 35, 48, 20])

In [74]:
arr = np.random.randint(5,200, (4,5)) # will generate the matrix
arr

array([[ 57, 112, 144, 125,  30],
       [  8, 104, 112, 141, 152],
       [171, 199,  94, 132, 103],
       [186, 100,  59, 105,  53]])

In [75]:
# Now lets create two arrays while using numpy functions 

In [76]:
array_arange = np.arange(16)

In [77]:
array_ranint = np.random.randint(0,100,10)

In [78]:
array_arange

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15])

In [79]:
array_ranint

array([ 0,  7, 77, 97, 20, 88, 29, 86,  2, 12])

#### lets use reshape() function 

##### The reshape() function
in NumPy is used to change the shape of an existing array without changing its data. 
This function is useful for transforming arrays into different dimensions or structures to fit the 
needs of various algorithms and data processing tasks.

SYNTAX : numpy.reshape(a, newshape, order='C')

Parameters:
#### a (required):
The array to be reshaped.
### newshape (required): 
The desired shape of the array. This can be specified as a tuple of integers or a single integer. One dimension can be specified as -1, which means it will be inferred based on the length of the array and the other dimensions.
### order (optional):
Determines the order in which the array is read/written. 'C' means row-major (C-style) order, while 'F' means column-major (Fortran-style) order. The default is 'C'.

In [81]:
array_arange.reshape(4,4) #Here we used reshape function , and transformed the one D to 4x4

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15]])

In [82]:
array_ranint.max() #max function will return you maximum value

97

In [84]:
array_ranint.min() # min function will return you minimum value 

0

In [87]:
#Next is argmax() and argmin() , is used to find the index location of max and min value

In [88]:
array_ranint.argmax()

3

In [89]:
array_ranint.argmin()

0

In [92]:
array_arange.size #checking the size of array

16

In [93]:
array_arange.shape #checking the shape of array

(16,)

In [95]:
array_arange.dtype #checking the data type of array

dtype('int32')

In [97]:
array_arange.reshape(4,4).shape #First reshape the array and then checking the size of array

(4, 4)

### PART 2

##### Indexing, Slicing, Broadcasting, Boolean Masking 

In [98]:
array_1d = np.array (([-10,-2,0,2,17,106,200])) #created an array

In [99]:
array_1d

array([-10,  -2,   0,   2,  17, 106, 200])

In [100]:
array_1d[0] #checking value at index 0

-10

In [101]:
array_1d[0:3] # will give values of index 0,1,2

array([-10,  -2,   0])

In [102]:
array_1d[0:3], array_1d

(array([-10,  -2,   0]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [103]:
array_1d[-2], array_1d # will give values of index -2

(106, array([-10,  -2,   0,   2,  17, 106, 200]))

In [104]:
array_1d[:2], array_1d # will give values of index 0,1 , excluding 2

(array([-10,  -2]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [105]:
array_1d[2:], array_1d # will give values of index 2 onwards

(array([  0,   2,  17, 106, 200]), array([-10,  -2,   0,   2,  17, 106, 200]))

In [107]:
array_2d = np.arange(24) 
array_2d

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23])

In [108]:
array_2d = np.arange(24).reshape(6,4) #creating 2D array while reshaping
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [111]:
#array_2d [row][column]
array_2d[2,3] #checking specific values by giving row and col values

11

In [112]:
array_2d[1] #will provide row at 1 location

array([4, 5, 6, 7])

In [114]:
row = 2
column = 3
array_2d[row,column] # we created row and column variables and then 
#called their values and will give you return value at that particular location

11

In [115]:
array_2d[2:4,2:4] # we are getting values 2 to 4 from rows , 2 to 4 from columns

array([[10, 11],
       [14, 15]])

### Broadcasting 

In [119]:
array_1d = np.arange(1,11)
array_1d

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [121]:
array_1d[0:5] = 200  #we have passed the slicer with the broadcast value 200, so from 0 to 4 indexx values will be replace by 200
array_1d

array([200, 200, 200, 200, 200,   6,   7,   8,   9,  10])

In [122]:
array_2d = np.ones((4,4))
array_2d

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

In [123]:
array_2d[0] = 100
array_2d

array([[100., 100., 100., 100.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.],
       [  1.,   1.,   1.,   1.]])

In [127]:
arr = np.arange(0,4)
arr

array([0, 1, 2, 3])

In [128]:
array_2d + arr #If we are adding arrays then second array supposed to have same number of columns

array([[100., 101., 102., 103.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.],
       [  1.,   2.,   3.,   4.]])

In [130]:
arrr = np.arange(4,8)
arrr

array([4, 5, 6, 7])

In [131]:
array_2d + arr +arrr #here we add three arrays 

array([[104., 106., 108., 110.],
       [  5.,   7.,   9.,  11.],
       [  5.,   7.,   9.,  11.],
       [  5.,   7.,   9.,  11.]])

In [132]:
np.arange(3)

array([0, 1, 2])

In [133]:
np.arange(3) + 5 #broadcarted with value 5 in row

array([5, 6, 7])

In [134]:
 np.ones((3,3))

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [135]:
 np.ones((3,3)) + np.arange(3)

array([[1., 2., 3.],
       [1., 2., 3.],
       [1., 2., 3.]])

In [143]:
np.arange((3)).reshape((3,1))

array([[0],
       [1],
       [2]])

In [144]:
np.arange(3)

array([0, 1, 2])

In [145]:
#Lets add above both cells
np.arange((3)).reshape((3,1)) + np.arange(3)

array([[0, 1, 2],
       [1, 2, 3],
       [2, 3, 4]])

In [146]:
arr

array([0, 1, 2, 3])

In [147]:
arr2 = np.arange(0,4)[:,np.newaxis]
arr2

array([[0],
       [1],
       [2],
       [3]])

In [148]:
arr2 +arr

array([[0, 1, 2, 3],
       [1, 2, 3, 4],
       [2, 3, 4, 5],
       [3, 4, 5, 6]])

### Fancy Indexing

In [149]:
array_2d = np.zeros((5,5))   #create a zero matrix
array_2d.shape[1]            #using shape attribute , get the number to run the loop
for i in range(array_2d.shape[1]): # using range in the loop
    array_2d[i] = i
array_2d                       # print the matrix

array([[0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.],
       [4., 4., 4., 4., 4.]])

In [150]:
array_2d[[1,2,3]] # will give rows 1, 2,3

array([[1., 1., 1., 1., 1.],
       [2., 2., 2., 2., 2.],
       [3., 3., 3., 3., 3.]])

In [151]:
array_2d[[3,0,1]]

array([[3., 3., 3., 3., 3.],
       [0., 0., 0., 0., 0.],
       [1., 1., 1., 1., 1.]])

In [158]:
#lets try another matrix
array_2d = np.arange(24) #created matrix
array_2d.shape = (6,4) # created shape of 6 rows 4 columns
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [161]:
array_2d[[2,4]] #getting rows

array([[ 8,  9, 10, 11],
       [16, 17, 18, 19]])

In [162]:
array_2d[[5,0]] #getting rows in any order

array([[20, 21, 22, 23],
       [ 0,  1,  2,  3]])

In [164]:
 array_2d[:,[2,3]] #getting columns

array([[ 2,  3],
       [ 6,  7],
       [10, 11],
       [14, 15],
       [18, 19],
       [22, 23]])

In [166]:
 array_2d[:,[3,0]] #getting columns in any order

array([[ 3,  0],
       [ 7,  4],
       [11,  8],
       [15, 12],
       [19, 16],
       [23, 20]])

### Boolean Masking

Boolean masking is very useful and handy when it comes to count, modify, extract or manipulate values
in an array based on some conditions or criteria. For eg, we want to count all the values greater than a certain value 
or we set a threshold and we want to get rid of outliers in our data. In numpy, boolean masking is often the most efficient way 
to accomplish such tasks. 

In [167]:
arr_1 = np.arange(1,11)

In [168]:
arr_1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [170]:
bool_mask = arr_1 > 3 # passing the condition 
bool_mask

array([False, False, False,  True,  True,  True,  True,  True,  True,
        True])

In [171]:
mod_2_mask_1d = 0 == arr_1 % 2 # checking odd or even

In [172]:
mod_2_mask_1d 

array([False,  True, False,  True, False,  True, False,  True, False,
        True])

In [174]:
ev_val = arr_1[mod_2_mask_1d ]
ev_val

array([ 2,  4,  6,  8, 10])

In [175]:
#creating 2 D array
array_2d = np.arange(24) 
array_2d.shape = (6,4)
mask_mod_2_2d = 0 == array_2d % 2 #Passing the mod operator to check odd or even

In [176]:
array_2d

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19],
       [20, 21, 22, 23]])

In [177]:
mask_mod_2_2d

array([[ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False],
       [ True, False,  True, False]])

In [178]:
array_2d[mask_mod_2_2d]

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22])

### Part 3  Numpy Operations

In [179]:
# Arithmatic Functions

arr = np.arange(4)

In [180]:
arr

array([0, 1, 2, 3])

In [181]:
arr +arr #Addition two arrays

array([0, 2, 4, 6])

In [182]:
arr * arr # Multiply Two arrays

array([0, 1, 4, 9])

In [185]:
arr - arr # Subtraction 

array([0, 0, 0, 0])

In [186]:
arr / arr

C:\Users\kanik\AppData\Local\Temp\ipykernel_19624\3001117470.py:1: RuntimeWarning: invalid value encountered in divide
  arr / arr


array([nan,  1.,  1.,  1.])

In [187]:
1/arr # So when we divide 0 by 1 , it will give infinity 

C:\Users\kanik\AppData\Local\Temp\ipykernel_19624\255282349.py:1: RuntimeWarning: divide by zero encountered in divide
  1/arr


array([       inf, 1.        , 0.5       , 0.33333333])

In [188]:
arr ** 2

array([0, 1, 4, 9])

In [189]:
2 * arr

array([0, 2, 4, 6])

In [190]:
10 * arr

array([ 0, 10, 20, 30])

In [191]:
# Universal Functions

In [192]:
# Square root 
np.sqrt(arr)

array([0.        , 1.        , 1.41421356, 1.73205081])

In [196]:
# max and min values 
np.max(arr),np.min(arr)

(3, 0)

In [197]:
#Ttrigno functions like sin, cos, tan etc
np.sin(arr)

array([0.        , 0.84147098, 0.90929743, 0.14112001])

In [198]:
#Calculate the all exponential values 
np.exp(arr)

array([ 1.        ,  2.71828183,  7.3890561 , 20.08553692])

In [199]:
np.log(arr)

C:\Users\kanik\AppData\Local\Temp\ipykernel_19624\3120950136.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(arr)


array([      -inf, 0.        , 0.69314718, 1.09861229])

In [200]:
np.deg2rad(arr) #coverting degrees to radiant

array([0.        , 0.01745329, 0.03490659, 0.05235988])

In [202]:
np.rad2deg(np.deg2rad(arr)) #AGAIN CONVERTING INTO THE SAME ONE 

array([0., 1., 2., 3.])